config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'admin', to: 'admins/homes#top'
  delete 'cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  get '/customers/my_page', to: 'public/customers#show'
  get '/customers/edit', to: 'public/customers#edit'
  patch '/customers', to: 'public/customers#update'
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  post '/orders/confirm', to: 'public/orders#confirm'
  get '/def', to: 'public/orders#complete'


  namespace :admins do
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: "public" do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :show]
  end


  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    "#{postal_code} #{address} #{name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def full_name
    "#{last_name}#{first_name}"
  end
  

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # has_many :orders, source: :order, foreign_key: 'customer_id', dependent: :destroy
  # has_many :order_details, through: :orders, source: :order_detail

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method:{ credit_card: 0, bank_transfer: 1}
  enum status:{ waiting: 0, confirm: 1, making: 2, ready_to_ship: 3, sent: 4}
  
  # @orders.order_details
# def self.order_details
#    OrderDetail.where(order_id: self.pluck(:id))
    # @order_details = OrderDetail.where(order_id: @orders.pluck(:id))
#  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status:{ unable: 0, waiting: 1, making: 2, complete: 3 }
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admins_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.all.order(id: "DESC")
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.joins(:order_details).find(params[:id])
    @order.update(order_params)
    @order.order_details.each do |order_detail|
      if order_detail.making_status == "unable"
        @order_detail = OrderDetail.find(order_detail.id)
        @order_detail.making_status = "waiting"
        @order_detail.save
      end
      
    end
    redirect_to admins_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end


  def after_sign_out_path_for(resource)
    case resource
    when Customer, :customer, :customers
      root_path
    when Admin, :admin, :admins
      new_admin_session_path
    end
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>ジャンル編集</h3>
      <%= form_with model: @genre, url: admins_genre_path, local: true do |f| %>
        <h4>ジャンル</h4>
        <%= f.text_field :name, class:"book-title-input" %>
        <div><%= f.radio_button :is_active, true %>有効</div>
        <div><%= f.radio_button :is_active, false %>無効</div>
        <%= f.submit '編集を保存する', class:"btn btn-primary" %>
      <% end %>
    </div>  
  </div>
</div>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h3>ジャンル一覧・追加</h3>
    </div>
  </div>

  <%= form_with model: @genre, url: admins_genres_path, local: true do |f| %>

  <h4>ジャンル</h4>
  <%= f.text_field :name, class:"book-title-input" %>

  <div><%= f.radio_button :is_active, true %>有効</div>
  <div><%= f.radio_button :is_active, false %>無効</div>
  <%= f.submit '追加', class:"btn btn-primary" %>
  <% end %>


  <table class="table table-striped">
  	<thead>
  		<tr>
  			<th>ジャンル</th>
  			<th>状態</th>
  			<th></th>
  		</tr>
  	</thead>
  	<tbody>
  	  <% @genres.each do |genre| %>
    		<tr>
    			<th><%= genre.name %></th>
    			<th>
    			  <%= genre.is_active == true ? "有効":"無効" %>
    			</th>
    			<th>
    			  <%= link_to "編集する", edit_admins_genre_path(genre), class: "btn btn-primary" %>
    			</th>
    		</tr>
  		<% end %>
  	</tbody>
  </table>
</div>

app/views/admins/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-2">
      <h1>管理者画面</h1>
      <h3>
        本日の注文件数
        <%= link_to admins_orders_path do %>
          <%= @orders.count %>
        <% end %>
        件
      </h3>
    </div>
  </div>
</div>

app/views/admins/items/edit.html.erb
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= @item.errors.count %>errors</h2>
      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <%= form_with model: @item, url: admins_item_path(@item), local: true do |f| %>
  	<div class="row">
  		<h1>商品編集</h1>
  	</div>
    <div class="row">
    	<div class="col-xs-3">
    		<%= attachment_image_tag @item, :image, :fill, 200, 200 %>
    		<%= f.attachment_field :image %>
    	</div>
    	<div class="col-xs-9">
    	  <table class="table table-striped">
    			<thead>
    				<tr>
    					<th>商品名</th>
    					<th><%= f.text_field :name %></th>
    				</tr>
    			</thead>
    			<tbody>
    				<tr>
    					<th>商品説明</th>
    					<th><%= f.text_field :introduction %></th>
    				</tr>
    				<tr>
    					<th>ジャンル</th>
    					<th><%= f.collection_select :genre_id, Genre.where(is_active: 1), :id, :name %></th>
    				</tr>
    				<tr>
    					<th>税抜き価格</th>
    					<th><%= f.number_field :price %>円</th>
    				</tr>
    				<tr>
    					<th>販売ステータス</th>
    					<th><%= f.select :is_active, [['販売停止中', 0], ['販売中', 1]] %></th>
    				</tr>
    			</tbody>
    		</table>
    	</div>
    </div>
  	<div class="row">
  		<div class="col-xs-3">
  			<%= f.submit '変更を保存', class:"btn btn-primary" %>
  		</div>
  	</div>
	<% end %>
</div>

app/views/admins/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3>商品一覧</h3>
    </div>
    <div class="col-xs-6">
      <h3><%= link_to "新規商品登録", new_admins_item_path %></h3>
    </div>
  </div>


  <table class="table table-striped">
  	<thead>
  		<tr>
  			<th>商品ID</th>
  			<th>商品名</th>
  			<th>税抜価格</th>
  			<th>ジャンル</th>
  			<th>ステータス</th>
  		</tr>
  	</thead>
  	<tbody>
  	  <% @items.each do |item| %>
    		<tr>
    			<td><%= item.id %></td>
    			<td>
    			  <%= link_to admins_item_path(item) do %>
    			    <%= item.name %>
    			  <% end %>
    			</td>
    			<td><%= item.price %></td>
    			<td><%= item.genre.name %></td>
    			<td>
					  <%= item.is_active == true ? "販売中":"販売停止中" %>
    			</th>
    		</tr>
  		<% end %>
  	</tbody>
  </table>
</div>

app/views/admins/items/new.html.erb
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <% if @item.errors.any? %>
          <div id="error_explanation">
            <h2><%= @item.errors.count %>errors</h2>
            <ul>
              <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <h4>新規商品登録</h4>
        <%= form_with model: @item, url: admins_items_path, local: true do |f| %>

        <%= f.attachment_field :image %>
        <h1>商品名</h1>
        <%= f.text_field :name, class: "form-control" %>
        <h1>商品説明</h1>
        <%= f.text_field :introduction, class: "form-control" %>
        <h1>ジャンル</h1>
        <%= f.collection_select :genre_id, Genre.where(is_active: 1), :id, :name %>
        <h1>税抜き価格</h1>
        <%= f.number_field :price, class: "form-control" %>
        <h1>販売ステータス</h1>
        <%= f.select :is_active, [['販売停止中', 0], ['販売中', 1]] %>

        </br><%= f.submit '追加', class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/admins/items/show.html.erb
<div class="container">
	<div class="row">
		<h1>商品詳細</h1>
	</div>
	<div class="row">
		<div class="col-xs-3">
			<%= attachment_image_tag @item, :image, :fill, 200, 200 %>
		</div>
		<div class="col-xs-9">
		  <table class="table table-striped">
				<thead>
					<tr>
						<th class="www">商品名</th>
						<th><%= @item.name %></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th>商品説明</th>
						<th><%= @item.introduction %></th>
					</tr>
					<tr>
						<th>ジャンル</th>
						<th><%= @item.genre.name %></th>
					</tr>
					<tr>
						<th>税込み価格</br>(税抜き価格)</th>
						<th><%= (@item.price*1.1).round(0) %>(<%= @item.price %>)円</th>
					</tr>
					<tr>
						<th>販売ステータス</th>
						<th><%= @item.is_active == true ? "販売中":"販売停止中" %></th>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-3">
			<%= link_to "編集する", edit_admins_item_path(@item), class: 'btn btn-default w-100px' %>
		</div>
	</div>
</div>

app/views/admins/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-1">
      <h3>注文履歴一覧</h3>
    </div>
  </div>
  <div class="row mt-30">
    <div class="col-xs-10 col-xs-offset-1">
      <table class="table table-striped table-bordered">
      	<thead>
      		<tr>
      			<th>購入日時</th>
      			<th>購入者</th>
      			<th>注文個数</th>
      			<th>注文ステータス</th>
      		</tr>
      	</thead>
      	<tbody>
      	  <% @orders.each do |order| %>
        		<tr>
        			<td>
        			  <%= link_to admins_order_path(order) do %>
        			    <%= order.created_at.strftime('%Y/%m/%d　%H:%M:%S') %>
        			  <% end %>
        			</td>
        			<td>
        			  <%= order.customer.full_name %>
        			</td>
        			<td>
        			  <% sum = 0 %>
        			  <% order.order_details.each do |order_detail| %>
        			    <% sum += order_detail.amount %>
        			  <% end %>
        			  <%= sum %>
        			</td>
        			<td><%= order.status_i18n %></td>
        		</tr>
      		<% end %>
      	</tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-11 col-xs-offset-1">
      <h1>注文履歴詳細</h1>
    </div>
  </div>
  <div class="row mt-20">
    <div class="col-xs-2">
      <h4 class="mt-0">購入者</h4>
    </div>
    <div class="col-xs-10">
      <%= link_to admins_customer_path(@order.customer) do %>
        <%= @order.customer.full_name %>
      <% end %>
    </div>
  </div>
  <div class="row mt-20">
    <div class="col-xs-2">
      <h4 class="mt-0">配送先</h4>
    </div>
    <div class="col-xs-10">
      <p>〒<%= @order.postal_code %> <%= @order.address %></p>
      <p><%= @order.name %></p>
    </div>
  </div>
  <div class="row mt-20">
    <div class="col-xs-2">
      <h4 class="mt-0">支払い方法</h4>
    </div>
    <div class="col-xs-10">
      <%= @order.payment_method_i18n %>
    </div>
  </div>
  <div class="row mt-20">
    <div class="col-xs-2">
      <h4 class="mt-0">注文ステータス</h4>
    </div>
    <div class="col-xs-10">
      <%= form_with model: @order, url: admins_order_path(@order), local: true do |f| %>
        <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
        <%= f.submit '更新', class:"btn btn-primary"%>
      <% end %>
    </div>
  </div>
  <div class="row mt-30">
    <div class="col-xs-8">
      <table class="table table-striped table-bordered">
      	<thead>
      		<tr>
      			<th>商品名</th>
      			<th>単価(税込)</th>
      			<th>数量</th>
      			<th>小計</th>
      			<th>制作ステータス</th>
      		</tr>
      	</thead>
      	<tbody>
      	  <% @order.order_details.each do |order_detail| %>
        		<tr>
        			<td>
        			  <%= order_detail.item.name %>
        			</td>
        			<td>
        			  <%= order_detail.price %>
        			</td>
        			<td>
        			  <%= order_detail.amount %>
        			</td>
        			<td>
        			  <%= order_detail.price * order_detail.amount %>
        			</td>
        			<td>
                <%= form_with model: order_detail, url: admins_order_detail_path(order_detail), local: true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                  <%= f.submit '更新', class:"btn btn-primary"%>
                <% end %>
        			</td>
        		</tr>
      		<% end %>
      	</tbody>
      </table>
    </div>
  </div>
</div>