config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'admin', to: 'admins/homes#top'
  delete 'cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  get '/customers/my_page', to: 'public/customers#show'
  get '/customers/edit', to: 'public/customers#edit'
  patch '/customers', to: 'public/customers#update'
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  post '/orders/confirm', to: 'public/orders#confirm'
  get '/def', to: 'public/orders#complete'


  namespace :admins do
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: "public" do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :show]
  end


  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # has_many :orders, source: :order, foreign_key: 'customer_id', dependent: :destroy
  # has_many :order_details, through: :orders, source: :order_detail

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admins_customers_path
  end

  private

    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
    end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_with model: @customer, url: admins_customer_path(@customer), local: true do |f| %>
        <table class="table table-striped">
        	<thead>
        		<tr>
        			<th>顧客ID</th>
        			<th><%= @customer.id %></th>
        		</tr>
        	</thead>
        	<tbody>
        		<tr>
        		  <td>氏名</td>
        			<td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
        		</tr>
        		<tr>
        		  <td>フリガナ</td>
        			<td><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></td>
        		</tr>
        		<tr>
        		  <td>郵便番号</td>
        			<td><%= f.text_field :postal_code %></td>
        		</tr>
        		<tr>
        		  <td>住所</td>
        			<td><%= f.text_field :address, class:"form-control" %></td>
        		</tr>
        		<tr>
        		  <td>電話番号</td>
        			<td><%= f.text_field :telephone_number, class:"form-control" %></td>
        		</tr>
        		<tr>
        		  <td>メールアドレス</td>
        			<td><%= f.email_field :email, class:"form-control" %></td>
        		</tr>
        		<tr>
        		  <td>会員ステータス</td>
        			<td><%= f.radio_button :is_deleted, false %>有効　<%= f.radio_button :is_deleted, true %>退会済み</td>
        		</tr>
        	</tbody>
        </table>
        <%= f.submit '変更を保存する', class:"btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3>会員一覧</h3>
    </div>
  </div>


  <table class="table table-striped">
  	<thead>
  		<tr>
  			<th>会員ID</th>
  			<th>氏名</th>
  			<th>メールアドレス</th>
  			<th>ステータス</th>
  		</tr>
  	</thead>
  	<tbody>
  	  <% @customers.each do |customer| %>
    		<tr>
    		  <td><%= customer.id %></td>
    			<td>
    			  <%= link_to admins_customer_path(customer) do %>
      			  <%= customer.last_name %>
      			  <%= customer.first_name %>
      			<% end %>
    			</td>
    			<td>
    			  <%= customer.email %>
    			</td>
    			<td><%= customer.is_deleted == true ? "退会済":"有効" %></td>
    		</tr>
  		<% end %>
  	</tbody>
  </table>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6">
      <table class="table table-striped">
      	<thead>
      		<tr>
      			<th>顧客ID</th>
      			<th><%= @customer.id %></th>
      		</tr>
      	</thead>
      	<tbody>
      		<tr>
      		  <td>氏名</td>
      			<td><%= @customer.last_name %> <%= @customer.first_name %></td>
      		</tr>
      		<tr>
      		  <td>フリガナ</td>
      			<td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      		</tr>
      		<tr>
      		  <td>郵便番号</td>
      			<td><%= @customer.postal_code %></td>
      		</tr>
      		<tr>
      		  <td>住所</td>
      			<td><%= @customer.address %></td>
      		</tr>
      		<tr>
      		  <td>電話番号</td>
      			<td><%= @customer.telephone_number %></td>
      		</tr>
      		<tr>
      		  <td>メールアドレス</td>
      			<td><%= @customer.email %></td>
      		</tr>
      	</tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-2">
      <%= link_to "編集する",edit_admins_customer_path(@customer), class: 'btn btn-default w-100px' %>
    </div>
    <div class="col-xs-2"></div>
  </div>
</div>