config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers
  # devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'public/homes#top'
  get 'about', to: 'public/homes#about'
  get 'admin', to: 'admins/homes#top'
  delete 'cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  get '/customers/my_page', to: 'public/customers#show'
  get '/customers/edit', to: 'public/customers#edit'
  patch '/customers', to: 'public/customers#update'
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  post '/orders/confirm', to: 'public/orders#confirm'
  get '/def', to: 'public/orders#complete'


  namespace :admins do
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end

  scope module: "public" do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :new, :create, :show]
  end


  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    "#{postal_code} #{address} #{name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def full_name
    "#{last_name}#{first_name}"
  end
  

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  # has_many :orders, source: :order, foreign_key: 'customer_id', dependent: :destroy
  # has_many :order_details, through: :orders, source: :order_detail

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment_method:{ credit_card: 0, bank_transfer: 1}
  enum status:{ waiting: 0, confirm: 1, making: 2, ready_to_ship: 3, sent: 4}
  
  # @orders.order_details
# def self.order_details
#    OrderDetail.where(order_id: self.pluck(:id))
    # @order_details = OrderDetail.where(order_id: @orders.pluck(:id))
#  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status:{ unable: 0, waiting: 1, making: 2, complete: 3 }
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number,:is_deleted])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end


  def after_sign_out_path_for(resource)
    case resource
    when Customer, :customer, :customers
      root_path
    when Admin, :admin, :admins
      new_admin_session_path
    end
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/order_details_helper.rb
module Admins::OrderDetailsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container header">
      <div class="row">
        <div class="col-xs-2"><%= link_to "ホーム", root_path, class: 'btn btn-default mt-30' %></div>
          <% if customer_signed_in? %>
            <div class="col-xs-10 mt-30">
              <ul class="header-list">
                <li>
                  <p>ようこそ<%= current_customer.full_name %>さん</p>
                </li>
                <li>
                  <%= link_to " マイページ", customers_my_page_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "商品一覧", items_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "カート", cart_items_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-default w-120px' %>
                </li>
              </ul>
            </div>
          <% elsif admin_signed_in? %>
            <div class="col-xs-10 mt-30">
              <ul class="header-list">
                <li>
                  <%= link_to "商品一覧", admins_items_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "ジャンル一覧", admins_genres_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "注文履歴一覧", admins_orders_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "会員一覧", admins_customers_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-default w-120px' %>
                </li>
              </ul>
            </div>
          <% else %>
            <div class="col-xs-10 mt-30">
              <ul class="header-list">
                <li>
                  <%= link_to "管理者", new_admin_session_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "About", about_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "商品一覧", items_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-default w-120px' %>
                </li>
                <li>
                  <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-default w-120px' %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
    <div class="row">
      <div class="col-xs-12 fo">
      </div>
    </div>
  </body>
</html>